spring:
  application:
    name: ecommerce
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:nacho
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update