DROP TABLE IF EXISTS PRICE;
DROP TABLE IF EXISTS BRAND;

CREATE TABLE BRAND
(
    ID BIGINT PRIMARY KEY
);

CREATE TABLE PRICE
(
    ID         BIGINT PRIMARY KEY,
    BRAND_ID   BIGINT,
    START_DATE DATETIME,
    END_DATE   DATETIME,
    PRODUCT_ID BIGINT,
    PRIORITY   INT,
    PRICE      DOUBLE,
    CURR       CHAR(3),
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID)
);
